project:
  type: website

website:
  google-analytics: "G-RQSB9K1JC6"
  title: "Test Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - page3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



